export const MAKE_LIST_REQUEST = 'MAKE_LIST_REQUEST';
export const MAKE_LIST_SUCCESS = 'MAKE_LIST_SUCCESS';
export const MAKE_LIST_FAIL = 'MAKE_LIST_FAIL';
export const MAKE_LIST_RESET = 'MAKE_LIST_RESET';
