export const YEAR_LIST_REQUEST = 'YEAR_LIST_REQUEST';
export const YEAR_LIST_SUCCESS = 'YEAR_LIST_SUCCESS';
export const YEAR_LIST_FAIL = 'YEAR_LIST_FAIL';
export const YEAR_LIST_RESET = 'YEAR_LIST_RESET';
